"""
test_semi_live_approval_cleanup.py - Test suite for semi-live approval workflow:
1. Video rendered and saved into Content Studio approval queue
2. Video file preserved while pending review
3. When approved, uploads to YouTube and auto-deletes the local rendered video
4. When rejected, deletes the local rendered video immediately
"""

import sys
import json
import base64
import subprocess
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
PUBLIC_DATA = PROJECT_ROOT / "public" / "data"
OUTPUTS = PROJECT_ROOT / "outputs"


def test_approval_workflow():
    OUTPUTS.mkdir(exist_ok=True)
    PUBLIC_DATA.mkdir(parents=True, exist_ok=True)

    q_file = PUBLIC_DATA / "approval_queue.json"
    media_file = PUBLIC_DATA / "recreated_media.json"

    # Backup existing
    q_backup = q_file.read_text(encoding="utf-8") if q_file.exists() else "[]"
    media_backup = media_file.read_text(encoding="utf-8") if media_file.exists() else "[]"

    try:
        # Step 1: Create a synthetic rendered video
        test_video = OUTPUTS / "test_semilive_render.mp4"
        test_video.write_bytes(b"TEST_MP4_VIDEO_PAYLOAD" * 200)
        test_srt = OUTPUTS / "subs_test_semilive_render.srt"
        test_srt.write_text("1\n00:00:00,000 --> 00:00:01,000\nCaption\n", encoding="utf-8")

        assert test_video.exists(), "Test video must exist before approval"
        assert test_srt.exists(), "Test SRT must exist before approval"

        test_id = "channel123_msg999_part001"
        queue_data = json.loads(q_backup)
        queue_data.append({
            "id": test_id,
            "timestamp": "2026-09-18T22:15:00",
            "video_path": "outputs/test_semilive_render.mp4",
            "full_video_path": str(test_video.resolve()),
            "public_url": "/outputs/test_semilive_render.mp4",
            "title": "Semi-Live Test Short",
            "metadata": {
                "title": "Semi-Live Test Short",
                "description": "Test description #Shorts",
                "tags": ["Shorts", "Test"],
                "privacy": "private",
            },
            "prediction": {"predicted_virality": 9.1},
            "upload_status": "pending_approval",
            "approved": None,
        })
        q_file.write_text(json.dumps(queue_data, indent=2), encoding="utf-8")

        # Step 2: Test Base64url ID encoding (as generated by server.mjs / store.ts)
        encoded_id = base64.urlsafe_b64encode(b"outputs/test_semilive_render.mp4|2026-09-18T22:15:00").decode().rstrip("=")

        # Step 3: Simulate operator approving via upload_approved_short.py with mock upload
        env = dict(sys.modules["os"].environ, YOUTUBE_MOCK_UPLOAD="1")
        proc = subprocess.run(
            [sys.executable, str(PROJECT_ROOT / "scripts" / "upload_approved_short.py"), encoded_id],
            capture_output=True,
            text=True,
            env=env,
        )

        assert proc.returncode == 0, f"Approval script failed: {proc.stderr}"
        res = json.loads(proc.stdout.strip())
        assert res.get("ok") is True, f"Expected ok=True, got: {res}"
        assert res.get("status") == "uploaded", f"Expected status=uploaded, got: {res.get('status')}"
        assert res.get("freed_bytes", 0) > 0, "Freed bytes must be > 0"

        # Step 4: Verify local files are deleted to free disk space
        assert not test_video.exists(), "Rendered .mp4 file must be deleted after upload to free space!"
        assert not test_srt.exists(), "Sidecar .srt file must be deleted after upload to free space!"

        # Step 5: Verify rejection cleanup
        test_reject_video = OUTPUTS / "test_semilive_reject.mp4"
        test_reject_video.write_bytes(b"REJECT_PAYLOAD" * 100)
        reject_id = "test_reject_item_999"

        queue_data = json.loads(q_file.read_text(encoding="utf-8"))
        queue_data.append({
            "id": reject_id,
            "timestamp": "2026-09-18T22:20:00",
            "video_path": "outputs/test_semilive_reject.mp4",
            "full_video_path": str(test_reject_video.resolve()),
            "public_url": "/outputs/test_semilive_reject.mp4",
            "title": "Rejected Short",
            "upload_status": "pending_approval",
            "approved": None,
        })
        q_file.write_text(json.dumps(queue_data, indent=2), encoding="utf-8")

        proc_rej = subprocess.run(
            [sys.executable, str(PROJECT_ROOT / "scripts" / "upload_approved_short.py"), reject_id, "--reject"],
            capture_output=True,
            text=True,
        )
        assert proc_rej.returncode == 0, f"Reject script failed: {proc_rej.stderr}"
        res_rej = json.loads(proc_rej.stdout.strip())
        assert res_rej.get("ok") is True
        assert res_rej.get("status") == "rejected"
        assert not test_reject_video.exists(), "Rendered video must be deleted upon rejection to free space!"

        print("\n[SUCCESS] All Semi-Live Approval & Space Cleanup tests PASSED!")

    finally:
        # Restore backups
        q_file.write_text(q_backup, encoding="utf-8")
        media_file.write_text(media_backup, encoding="utf-8")


if __name__ == "__main__":
    test_approval_workflow()
